INSERT INTO cities VALUES ("Aberdeen");
INSERT INTO cities VALUES ("Abilene");
INSERT INTO cities VALUES ("Akron");
INSERT INTO cities VALUES ("Albany");
INSERT INTO cities VALUES ("Albuquerque");
INSERT INTO cities VALUES ("Alexandria");
INSERT INTO cities VALUES ("Allentown");
INSERT INTO cities VALUES ("Amarillo");
INSERT INTO cities VALUES ("Anaheim");
INSERT INTO cities VALUES ("Anchorage");
INSERT INTO cities VALUES ("Ann Arbor");
INSERT INTO cities VALUES ("Antioch");
INSERT INTO cities VALUES ("Apple Valley");
INSERT INTO cities VALUES ("Appleton");
INSERT INTO cities VALUES ("Arlington");
INSERT INTO cities VALUES ("Arvada");
INSERT INTO cities VALUES ("Asheville");
INSERT INTO cities VALUES ("Athens");
INSERT INTO cities VALUES ("Atlanta");
INSERT INTO cities VALUES ("Atlantic City");
INSERT INTO cities VALUES ("Augusta");
INSERT INTO cities VALUES ("Aurora");
INSERT INTO cities VALUES ("Austin");
INSERT INTO cities VALUES ("Bakersfield");
INSERT INTO cities VALUES ("Baltimore");
INSERT INTO cities VALUES ("Barnstable");
INSERT INTO cities VALUES ("Baton Rouge");
INSERT INTO cities VALUES ("Beaumont");
INSERT INTO cities VALUES ("Bel Air");
INSERT INTO cities VALUES ("Bellevue");
INSERT INTO cities VALUES ("Berkeley");
INSERT INTO cities VALUES ("Bethlehem");
INSERT INTO cities VALUES ("Billings");
INSERT INTO cities VALUES ("Birmingham");
INSERT INTO cities VALUES ("Bloomington");
INSERT INTO cities VALUES ("Boise");
INSERT INTO cities VALUES ("Boise City");
INSERT INTO cities VALUES ("Bonita Springs");
INSERT INTO cities VALUES ("Boston");
INSERT INTO cities VALUES ("Boulder");
INSERT INTO cities VALUES ("Bradenton");
INSERT INTO cities VALUES ("Bremerton");
INSERT INTO cities VALUES ("Bridgeport");
INSERT INTO cities VALUES ("Brighton");
INSERT INTO cities VALUES ("Brownsville");
INSERT INTO cities VALUES ("Bryan");
INSERT INTO cities VALUES ("Buffalo");
INSERT INTO cities VALUES ("Burbank");
INSERT INTO cities VALUES ("Burlington");
INSERT INTO cities VALUES ("Cambridge");
INSERT INTO cities VALUES ("Canton");
INSERT INTO cities VALUES ("Cape Coral");
INSERT INTO cities VALUES ("Carrollton");
INSERT INTO cities VALUES ("Cary");
INSERT INTO cities VALUES ("Cathedral City");
INSERT INTO cities VALUES ("Cedar Rapids");
INSERT INTO cities VALUES ("Champaign");
INSERT INTO cities VALUES ("Chandler");
INSERT INTO cities VALUES ("Charleston");
INSERT INTO cities VALUES ("Charlotte");
INSERT INTO cities VALUES ("Chattanooga");
INSERT INTO cities VALUES ("Chesapeake");
INSERT INTO cities VALUES ("Chicago");
INSERT INTO cities VALUES ("Chula Vista");
INSERT INTO cities VALUES ("Cincinnati");
INSERT INTO cities VALUES ("Clarke County");
INSERT INTO cities VALUES ("Clarksville");
INSERT INTO cities VALUES ("Clearwater");
INSERT INTO cities VALUES ("Cleveland");
INSERT INTO cities VALUES ("College Station");
INSERT INTO cities VALUES ("Colorado Springs");
INSERT INTO cities VALUES ("Columbia");
INSERT INTO cities VALUES ("Columbus");
INSERT INTO cities VALUES ("Concord");
INSERT INTO cities VALUES ("Coral Springs");
INSERT INTO cities VALUES ("Corona");
INSERT INTO cities VALUES ("Corpus Christi");
INSERT INTO cities VALUES ("Costa Mesa");
INSERT INTO cities VALUES ("Dallas");
INSERT INTO cities VALUES ("Daly City");
INSERT INTO cities VALUES ("Danbury");
INSERT INTO cities VALUES ("Davenport");
INSERT INTO cities VALUES ("Davidson County");
INSERT INTO cities VALUES ("Dayton");
INSERT INTO cities VALUES ("Daytona Beach");
INSERT INTO cities VALUES ("Deltona");
INSERT INTO cities VALUES ("Denton");
INSERT INTO cities VALUES ("Denver");
INSERT INTO cities VALUES ("Des Moines");
INSERT INTO cities VALUES ("Detroit");
INSERT INTO cities VALUES ("Downey");
INSERT INTO cities VALUES ("Duluth");
INSERT INTO cities VALUES ("Durham");
INSERT INTO cities VALUES ("El Monte");
INSERT INTO cities VALUES ("El Paso");
INSERT INTO cities VALUES ("Elizabeth");
INSERT INTO cities VALUES ("Elk Grove");
INSERT INTO cities VALUES ("Elkhart");
INSERT INTO cities VALUES ("Erie");
INSERT INTO cities VALUES ("Escondido");
INSERT INTO cities VALUES ("Eugene");
INSERT INTO cities VALUES ("Evansville");
INSERT INTO cities VALUES ("Fairfield");
INSERT INTO cities VALUES ("Fargo");
INSERT INTO cities VALUES ("Fayetteville");
INSERT INTO cities VALUES ("Fitchburg");
INSERT INTO cities VALUES ("Flint");
INSERT INTO cities VALUES ("Fontana");
INSERT INTO cities VALUES ("Fort Collins");
INSERT INTO cities VALUES ("Fort Lauderdale");
INSERT INTO cities VALUES ("Fort Smith");
INSERT INTO cities VALUES ("Fort Walton Beach");
INSERT INTO cities VALUES ("Fort Wayne");
INSERT INTO cities VALUES ("Fort Worth");
INSERT INTO cities VALUES ("Frederick");
INSERT INTO cities VALUES ("Fremont");
INSERT INTO cities VALUES ("Fresno");
INSERT INTO cities VALUES ("Fullerton");
INSERT INTO cities VALUES ("Gainesville");
INSERT INTO cities VALUES ("Garden Grove");
INSERT INTO cities VALUES ("Garland");
INSERT INTO cities VALUES ("Gastonia");
INSERT INTO cities VALUES ("Gilbert");
INSERT INTO cities VALUES ("Glendale");
INSERT INTO cities VALUES ("Grand Prairie");
INSERT INTO cities VALUES ("Grand Rapids");
INSERT INTO cities VALUES ("Grayslake");
INSERT INTO cities VALUES ("Green Bay");
INSERT INTO cities VALUES ("GreenBay");
INSERT INTO cities VALUES ("Greensboro");
INSERT INTO cities VALUES ("Greenville");
INSERT INTO cities VALUES ("Gulfport-Biloxi");
INSERT INTO cities VALUES ("Hagerstown");
INSERT INTO cities VALUES ("Hampton");
INSERT INTO cities VALUES ("Harlingen");
INSERT INTO cities VALUES ("Harrisburg");
INSERT INTO cities VALUES ("Hartford");
INSERT INTO cities VALUES ("Havre de Grace");
INSERT INTO cities VALUES ("Hayward");
INSERT INTO cities VALUES ("Hemet");
INSERT INTO cities VALUES ("Henderson");
INSERT INTO cities VALUES ("Hesperia");
INSERT INTO cities VALUES ("Hialeah");
INSERT INTO cities VALUES ("Hickory");
INSERT INTO cities VALUES ("High Point");
INSERT INTO cities VALUES ("Hollywood");
INSERT INTO cities VALUES ("Honolulu");
INSERT INTO cities VALUES ("Houma");
INSERT INTO cities VALUES ("Houston");
INSERT INTO cities VALUES ("Howell");
INSERT INTO cities VALUES ("Huntington");
INSERT INTO cities VALUES ("Huntington Beach");
INSERT INTO cities VALUES ("Huntsville");
INSERT INTO cities VALUES ("Independence");
INSERT INTO cities VALUES ("Indianapolis");
INSERT INTO cities VALUES ("Inglewood");
INSERT INTO cities VALUES ("Irvine");
INSERT INTO cities VALUES ("Irving");
INSERT INTO cities VALUES ("Jackson");
INSERT INTO cities VALUES ("Jacksonville");
INSERT INTO cities VALUES ("Jefferson");
INSERT INTO cities VALUES ("Jersey City");
INSERT INTO cities VALUES ("Johnson City");
INSERT INTO cities VALUES ("Joliet");
INSERT INTO cities VALUES ("Kailua");
INSERT INTO cities VALUES ("Kalamazoo");
INSERT INTO cities VALUES ("Kaneohe");
INSERT INTO cities VALUES ("Kansas City");
INSERT INTO cities VALUES ("Kennewick");
INSERT INTO cities VALUES ("Kenosha");
INSERT INTO cities VALUES ("Killeen");
INSERT INTO cities VALUES ("Kissimmee");
INSERT INTO cities VALUES ("Knoxville");
INSERT INTO cities VALUES ("Lacey");
INSERT INTO cities VALUES ("Lafayette");
INSERT INTO cities VALUES ("Lake Charles");
INSERT INTO cities VALUES ("Lakeland");
INSERT INTO cities VALUES ("Lakewood");
INSERT INTO cities VALUES ("Lancaster");
INSERT INTO cities VALUES ("Lansing");
INSERT INTO cities VALUES ("Laredo");
INSERT INTO cities VALUES ("Las Cruces");
INSERT INTO cities VALUES ("Las Vegas");
INSERT INTO cities VALUES ("Layton");
INSERT INTO cities VALUES ("Leominster");
INSERT INTO cities VALUES ("Lewisville");
INSERT INTO cities VALUES ("Lexington");
INSERT INTO cities VALUES ("Lincoln");
INSERT INTO cities VALUES ("Little Rock");
INSERT INTO cities VALUES ("Long Beach");
INSERT INTO cities VALUES ("Lorain");
INSERT INTO cities VALUES ("Los Angeles");
INSERT INTO cities VALUES ("Louisville");
INSERT INTO cities VALUES ("Lowell");
INSERT INTO cities VALUES ("Lubbock");
INSERT INTO cities VALUES ("Macon");
INSERT INTO cities VALUES ("Madison");
INSERT INTO cities VALUES ("Manchester");
INSERT INTO cities VALUES ("Marina");
INSERT INTO cities VALUES ("Marysville");
INSERT INTO cities VALUES ("McAllen");
INSERT INTO cities VALUES ("McHenry");
INSERT INTO cities VALUES ("Medford");
INSERT INTO cities VALUES ("Melbourne");
INSERT INTO cities VALUES ("Memphis");
INSERT INTO cities VALUES ("Merced");
INSERT INTO cities VALUES ("Mesa");
INSERT INTO cities VALUES ("Mesquite");
INSERT INTO cities VALUES ("Miami");
INSERT INTO cities VALUES ("Milwaukee");
INSERT INTO cities VALUES ("Minneapolis");
INSERT INTO cities VALUES ("Miramar");
INSERT INTO cities VALUES ("Mission Viejo");
INSERT INTO cities VALUES ("Mobile");
INSERT INTO cities VALUES ("Modesto");
INSERT INTO cities VALUES ("Monroe");
INSERT INTO cities VALUES ("Monterey");
INSERT INTO cities VALUES ("Montgomery");
INSERT INTO cities VALUES ("Moreno Valley");
INSERT INTO cities VALUES ("Murfreesboro");
INSERT INTO cities VALUES ("Murrieta");
INSERT INTO cities VALUES ("Muskegon");
INSERT INTO cities VALUES ("Myrtle Beach");
INSERT INTO cities VALUES ("Naperville");
INSERT INTO cities VALUES ("Naples");
INSERT INTO cities VALUES ("Nashua");
INSERT INTO cities VALUES ("Nashville");
INSERT INTO cities VALUES ("New Bedford");
INSERT INTO cities VALUES ("New Haven");
INSERT INTO cities VALUES ("New London");
INSERT INTO cities VALUES ("New Orleans");
INSERT INTO cities VALUES ("New York");
INSERT INTO cities VALUES ("New York City");
INSERT INTO cities VALUES ("Newark");
INSERT INTO cities VALUES ("Newburgh");
INSERT INTO cities VALUES ("Newport News");
INSERT INTO cities VALUES ("Norfolk");
INSERT INTO cities VALUES ("Normal");
INSERT INTO cities VALUES ("Norman");
INSERT INTO cities VALUES ("North Charleston");
INSERT INTO cities VALUES ("North Las Vegas");
INSERT INTO cities VALUES ("North Port");
INSERT INTO cities VALUES ("Norwalk");
INSERT INTO cities VALUES ("Norwich");
INSERT INTO cities VALUES ("Oakland");
INSERT INTO cities VALUES ("Ocala");
INSERT INTO cities VALUES ("Oceanside");
INSERT INTO cities VALUES ("Odessa");
INSERT INTO cities VALUES ("Ogden");
INSERT INTO cities VALUES ("Oklahoma City");
INSERT INTO cities VALUES ("Olathe");
INSERT INTO cities VALUES ("Olympia");
INSERT INTO cities VALUES ("Omaha");
INSERT INTO cities VALUES ("Ontario");
INSERT INTO cities VALUES ("Orange");
INSERT INTO cities VALUES ("Orem");
INSERT INTO cities VALUES ("Orlando");
INSERT INTO cities VALUES ("Overland Park");
INSERT INTO cities VALUES ("Oxnard");
INSERT INTO cities VALUES ("Palm Bay");
INSERT INTO cities VALUES ("Palm Springs");
INSERT INTO cities VALUES ("Palmdale");
INSERT INTO cities VALUES ("Panama City");
INSERT INTO cities VALUES ("Pasadena");
INSERT INTO cities VALUES ("Paterson");
INSERT INTO cities VALUES ("Pembroke Pines");
INSERT INTO cities VALUES ("Pensacola");
INSERT INTO cities VALUES ("Peoria");
INSERT INTO cities VALUES ("Philadelphia");
INSERT INTO cities VALUES ("Phoenix");
INSERT INTO cities VALUES ("Pittsburgh");
INSERT INTO cities VALUES ("Plano");
INSERT INTO cities VALUES ("Pomona");
INSERT INTO cities VALUES ("Pompano Beach");
INSERT INTO cities VALUES ("Port Arthur");
INSERT INTO cities VALUES ("Port Orange");
INSERT INTO cities VALUES ("Port Saint Lucie");
INSERT INTO cities VALUES ("Port St. Lucie");
INSERT INTO cities VALUES ("Portland");
INSERT INTO cities VALUES ("Portsmouth");
INSERT INTO cities VALUES ("Poughkeepsie");
INSERT INTO cities VALUES ("Providence");
INSERT INTO cities VALUES ("Provo");
INSERT INTO cities VALUES ("Pueblo");
INSERT INTO cities VALUES ("Punta Gorda");
INSERT INTO cities VALUES ("Racine");
INSERT INTO cities VALUES ("Raleigh");
INSERT INTO cities VALUES ("Rancho Cucamonga");
INSERT INTO cities VALUES ("Reading");
INSERT INTO cities VALUES ("Redding");
INSERT INTO cities VALUES ("Reno");
INSERT INTO cities VALUES ("Richland");
INSERT INTO cities VALUES ("Richmond");
INSERT INTO cities VALUES ("Richmond County");
INSERT INTO cities VALUES ("Riverside");
INSERT INTO cities VALUES ("Roanoke");
INSERT INTO cities VALUES ("Rochester");
INSERT INTO cities VALUES ("Rockford");
INSERT INTO cities VALUES ("Roseville");
INSERT INTO cities VALUES ("Round Lake Beach");
INSERT INTO cities VALUES ("Sacramento");
INSERT INTO cities VALUES ("Saginaw");
INSERT INTO cities VALUES ("Saint Louis");
INSERT INTO cities VALUES ("Saint Paul");
INSERT INTO cities VALUES ("Saint Petersburg");
INSERT INTO cities VALUES ("Salem");
INSERT INTO cities VALUES ("Salinas");
INSERT INTO cities VALUES ("Salt Lake City");
INSERT INTO cities VALUES ("San Antonio");
INSERT INTO cities VALUES ("San Bernardino");
INSERT INTO cities VALUES ("San Buenaventura");
INSERT INTO cities VALUES ("San Diego");
INSERT INTO cities VALUES ("San Francisco");
INSERT INTO cities VALUES ("San Jose");
INSERT INTO cities VALUES ("Santa Ana");
INSERT INTO cities VALUES ("Santa Barbara");
INSERT INTO cities VALUES ("Santa Clara");
INSERT INTO cities VALUES ("Santa Clarita");
INSERT INTO cities VALUES ("Santa Cruz");
INSERT INTO cities VALUES ("Santa Maria");
INSERT INTO cities VALUES ("Santa Rosa");
INSERT INTO cities VALUES ("Sarasota");
INSERT INTO cities VALUES ("Savannah");
INSERT INTO cities VALUES ("Scottsdale");
INSERT INTO cities VALUES ("Scranton");
INSERT INTO cities VALUES ("Seaside");
INSERT INTO cities VALUES ("Seattle");
INSERT INTO cities VALUES ("Sebastian");
INSERT INTO cities VALUES ("Shreveport");
INSERT INTO cities VALUES ("Simi Valley");
INSERT INTO cities VALUES ("Sioux City");
INSERT INTO cities VALUES ("Sioux Falls");
INSERT INTO cities VALUES ("South Bend");
INSERT INTO cities VALUES ("South Lyon");
INSERT INTO cities VALUES ("Spartanburg");
INSERT INTO cities VALUES ("Spokane");
INSERT INTO cities VALUES ("Springdale");
INSERT INTO cities VALUES ("Springfield");
INSERT INTO cities VALUES ("St. Louis");
INSERT INTO cities VALUES ("St. Paul");
INSERT INTO cities VALUES ("St. Petersburg");
INSERT INTO cities VALUES ("Stamford");
INSERT INTO cities VALUES ("Sterling Heights");
INSERT INTO cities VALUES ("Stockton");
INSERT INTO cities VALUES ("Sunnyvale");
INSERT INTO cities VALUES ("Syracuse");
INSERT INTO cities VALUES ("Tacoma");
INSERT INTO cities VALUES ("Tallahassee");
INSERT INTO cities VALUES ("Tampa");
INSERT INTO cities VALUES ("Temecula");
INSERT INTO cities VALUES ("Tempe");
INSERT INTO cities VALUES ("Thornton");
INSERT INTO cities VALUES ("Thousand Oaks");
INSERT INTO cities VALUES ("Toledo");
INSERT INTO cities VALUES ("Topeka");
INSERT INTO cities VALUES ("Torrance");
INSERT INTO cities VALUES ("Trenton");
INSERT INTO cities VALUES ("Tucson");
INSERT INTO cities VALUES ("Tulsa");
INSERT INTO cities VALUES ("Tuscaloosa");
INSERT INTO cities VALUES ("Tyler");
INSERT INTO cities VALUES ("Utica");
INSERT INTO cities VALUES ("Vallejo");
INSERT INTO cities VALUES ("Vancouver");
INSERT INTO cities VALUES ("Vero Beach");
INSERT INTO cities VALUES ("Victorville");
INSERT INTO cities VALUES ("Virginia Beach");
INSERT INTO cities VALUES ("Visalia");
INSERT INTO cities VALUES ("Waco");
INSERT INTO cities VALUES ("Warren");
INSERT INTO cities VALUES ("Washington");
INSERT INTO cities VALUES ("Waterbury");
INSERT INTO cities VALUES ("Waterloo");
INSERT INTO cities VALUES ("West Covina");
INSERT INTO cities VALUES ("West Valley City");
INSERT INTO cities VALUES ("Westminster");
INSERT INTO cities VALUES ("Wichita");
INSERT INTO cities VALUES ("Wilmington");
INSERT INTO cities VALUES ("Winston");
INSERT INTO cities VALUES ("Winter Haven");
INSERT INTO cities VALUES ("Worcester");
INSERT INTO cities VALUES ("Yakima");
INSERT INTO cities VALUES ("Yonkers");
INSERT INTO cities VALUES ("York");
INSERT INTO cities VALUES ("Youngstown");
